name: CurseOfVanishing
version: 1.0
main: me.xenkys.curseofvanishing.Main
api-version: "1.20"
commands:
  vanish:
    description: Vanish from other players
    usage: /<command>
    permission: curseofvanishing.vanish.use
    aliases:
      - v